package net.halbear.aotg.utility.DataGenerators;

import net.halbear.aotg.AgeoftheGods;
import net.halbear.aotg.registries.ModBlocks;
import net.halbear.aotg.registries.ModItems;
import net.minecraft.client.data.models.BlockModelGenerators;
import net.minecraft.client.data.models.ItemModelGenerators;
import net.minecraft.client.data.models.ModelProvider;
import net.minecraft.client.data.models.MultiVariant;
import net.minecraft.client.data.models.blockstates.MultiVariantGenerator;
import net.minecraft.client.data.models.model.ModelTemplate;
import net.minecraft.client.data.models.model.ModelTemplates;
import net.minecraft.client.data.models.model.TextureMapping;
import net.minecraft.client.data.models.model.TextureSlot;
import net.minecraft.client.renderer.Sheets;
import net.minecraft.client.renderer.block.dispatch.Variant;
import net.minecraft.client.resources.model.sprite.Material;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.Block;

public class AOTGModelProvider extends ModelProvider {
    public AOTGModelProvider(PackOutput output){super(output, AgeoftheGods.MODID);}

    @Override
    protected void registerModels(BlockModelGenerators BlockModels, ItemModelGenerators itemModels){
     //   BlockModels.createTrivialCube(ModBlocks.LIMESTONE_BLOCK.get());
     //   BlockModels.createTrivialCube(ModBlocks.LIMESTONE_GRASS_BLOCK.get());
     //   BlockModels.createTrivialCube(ModBlocks.SHALE_BLOCK.get());
     //   BlockModels.createTrivialCube(ModBlocks.OLIVE_LEAVES.get());
     //   BlockModels.createTrivialCube(ModBlocks.SHALE_GRASS_BLOCK.get());

   }
}
